### PR TITLE
Add dynamic emoji

### PR DESCRIPTION
**Pull request by tonyxwz**
at half hour precision

### CODE REVIEW

**Comment by enricobacis** [comment]
Very nice, my only concern is that this will make the section jump in size every half an hour to accommodate for the extra characters. Is that intentional?

**Comment by tonyxwz** [comment]
No, the clock symbol will always appear. For time such as 12:20, the symbol is :clock12:. For time such as 12:40, the symbol is :clock1230:.

**Comment by enricobacis** [comment]
Ah, sweet (I admit that I haven't read the code too thoroughly before posting my previous comment). I'm now thinking that if someone is using non-emoji font, they will have a not nice experience. Maybe it's better to default to non using this feature and then document it in the README. What do you think?

**Comment by tonyxwz** [comment]
I agree. I will update it later.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Pull request closed without merging**
